version: '3.8'

services:
  kong-database:
    container_name: kong-database
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kongpass
    image: postgres:12
    networks:
      - kong-net
    ports:
      - 5432:5432

  kong-migration:
    command:
      - kong
      - migrations
      - bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PASSWORD: test
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpass
    image: kong/kong:2.8.0
    networks:
      - kong-net

  kong-gateway:
    container_name: kong-gateway
    build: .
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_PLUGINS: bundled, oidc
      KONG_DATABASE: postgres
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
    networks:
      - kong-net
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004


  #######################################
  # Konga: Latest Version
  # Currently supports upto postgres 9.6
  # Hence separate db for Konga
  #######################################
  konga-database:
    container_name: konga-database
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kongpass
    image: postgres:9.6
    networks:
      - kong-net
    ports:
      - 5433:5432


  konga-prepare:
    image: pantsel/konga:next
    command: "-c prepare -a postgres -u postgresql://kong:kongpass@konga-database:5432/konga_db"
    networks:
      - kong-net
    links:
      - konga-database
    depends_on:
      - konga-database

  konga:
    image: pantsel/konga:next
    restart: always
    networks:
        - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: konga-database
      DB_USER: kong
      DB_PASSWORD: kongpass
      DB_DATABASE: konga_db
      # DB_IS_PG12_OR_NEWER: true
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      NODE_ENV: production
    depends_on:
      - konga-database
    ports:
      - "1337:1337"


  #######################################
  # Konga: Future Version
  # With support for postgres 12+
  # Can use same DB as kong database
  #######################################


  # konga-prepare:
  #   image: pantsel/konga:next
  #   environment:
  #     # DB_IS_PG12_OR_NEWER: true
  #   command: "-c prepare -a postgres -u postgresql://kong:kongpass@kong-database:5432/konga_db"
  #   networks:
  #     - kong-net
  #   links:
  #     - kong-database
  #   depends_on:
  #     - kong-database

  # konga:
  #   image: pantsel/konga:next
  #   restart: always
  #   networks:
  #       - kong-net
  #   environment:
  #     DB_ADAPTER: postgres
  #     DB_HOST: konga-database
  #     DB_USER: kong
  #     DB_PASSWORD: kongpass
  #     DB_DATABASE: konga_db
  #     # DB_IS_PG12_OR_NEWER: true
  #     TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
  #     NODE_ENV: production
  #   depends_on:
  #     - kong-database
  #   ports:
  #     - "1337:1337"

networks:
  kong-net:
    driver: bridge

